server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: LIU18959297292
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userServer  # 服务名称，在euraka中展示
  cloud:
    nacos:
      server-addr: 192.168.3.145:8848 # nacos服务地址
      discovery:
        cluster-name: FJ # nacos集群名称
#      config:
#        import=nacos: 192.168.3.145:8848
#          nacos: application.yml # nacos配置中心地址
#        import-check:
#          enabled: false # 是否开启配置中心检查
#        group: DEFAULT_GROUP # nacos配置中心组
#        file-extension: yml # nacos配置中心文件类型
#        namespace: dev # nacos配置中心命名空间
#========================================================
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
#========================================================
#mybatis:
#  type-aliases-package: wo1261931780.userService.user.pojo
#  configuration:
#    map-underscore-to-camel-case: true
#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#========================================================
#要将服务注册到eureka上，需要在application.yml中添加以下内容：
#注册之前，需要在pom中引入客户端依赖
#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#========================================================
#pattern:
#  name: 本地环境local
