feign:
  client:
    config:
      default:
        logger-level: basic
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
server:
  port: 8081
# 如果您是将OpenFeign客户端独立出一个模块,且这个模块只是用于发起远程调用,不提供服务,则它不需要注册到Nacos中。
#
#注册到Nacos的主要是服务提供方,以便服务消费方可以发现并调用它。
#
#对于OpenFeign客户端模块,它仅充当一个声明式的HTTP客户端。你只需要在服务消费方应用中引入这个OpenFeign模块并使用它调用其他服务即可。
#
#具体来说,在使用OpenFeign的服务消费方应用中,需要做以下配置:
#
#1. 引入OpenFeign客户端模块依赖
#
#2. 在主应用中添加@EnableFeignClients注解来扫描OpenFeign客户端
#
#3. 配置Nacos服务注册发现(消费方需要注册到Nacos)
#
#4. 通过@FeignClient使用OpenFeign接口发起远程调用
#
#而OpenFeign客户端模块本身不需要也不应该注册到Nacos。它仅通过Nacos服务发现来定位服务提供方。
#
#所以综上,OpenFeign客户端独立模块不需要注册到Nacos中,只需要部署和引入到实际的服务消费方应用中使用即可。
